<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-17T14:12:19 PDT" name="Suite" finished-at="2023-07-17T14:12:24 PDT" duration-ms="5634">
    <groups>
    </groups>
    <test started-at="2023-07-17T14:12:19 PDT" name="Test" finished-at="2023-07-17T14:12:24 PDT" duration-ms="5634">
      <class name="api.test.TestBookingFlow">
        <test-method is-config="true" signature="setup()[pri:0, instance:api.test.TestBookingFlow@2892d68]" started-at="2023-07-17T14:12:19 PDT" name="setup" finished-at="2023-07-17T14:12:22 PDT" duration-ms="3312" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="test_CreateBooking()[pri:1, instance:api.test.TestBookingFlow@2892d68]" started-at="2023-07-17T14:12:22 PDT" name="test_CreateBooking" finished-at="2023-07-17T14:12:23 PDT" duration-ms="507" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_CreateBooking -->
        <test-method signature="test_GetBooking()[pri:2, instance:api.test.TestBookingFlow@2892d68]" started-at="2023-07-17T14:12:23 PDT" name="test_GetBooking" finished-at="2023-07-17T14:12:23 PDT" depends-on-methods="api.test.TestBookingFlow.test_CreateBooking" duration-ms="505" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_GetBooking -->
        <test-method signature="test_PartialUpdateBooking()[pri:3, instance:api.test.TestBookingFlow@2892d68]" started-at="2023-07-17T14:12:24 PDT" name="test_PartialUpdateBooking" finished-at="2023-07-17T14:12:24 PDT" depends-on-methods="api.test.TestBookingFlow.test_CreateBooking" duration-ms="494" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [405]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at api.test.TestBookingFlow.test_PartialUpdateBooking(TestBookingFlow.java:64)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_PartialUpdateBooking -->
        <test-method signature="test_DeleteBooking()[pri:4, instance:api.test.TestBookingFlow@2892d68]" started-at="2023-07-17T14:12:24 PDT" name="test_DeleteBooking" finished-at="2023-07-17T14:12:24 PDT" depends-on-methods="api.test.TestBookingFlow.test_CreateBooking" duration-ms="435" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_DeleteBooking -->
      </class> <!-- api.test.TestBookingFlow -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
